"""Description for ConsumerProducts Entities."""

from __future__ import annotations

from typing import TYPE_CHECKING

from homeassistant.components.binary_sensor.const import BinarySensorDeviceClass
from homeassistant.components.number import NumberDeviceClass, NumberMode
from homeassistant.components.sensor import SensorDeviceClass, SensorStateClass
from homeassistant.components.switch.const import SwitchDeviceClass
from homeassistant.const import EntityCategory, UnitOfVolume

from .descriptions_definitions import (
    HCBinarySensorEntityDescription,
    HCNumberEntityDescription,
    HCSelectEntityDescription,
    HCSensorEntityDescription,
    HCSwitchEntityDescription,
)

if TYPE_CHECKING:
    from .descriptions_definitions import _EntityDescriptionsDefinitionsType

CONSUMER_PRODUCTS_ENTITY_DESCRIPTIONS: _EntityDescriptionsDefinitionsType = {
    "binary_sensor": [
        HCBinarySensorEntityDescription(
            key="binary_sensor_coffee_brewing_unit_missing",
            entity="ConsumerProducts.CoffeeMaker.Event.BrewingUnitIsMissing",
            device_class=BinarySensorDeviceClass.PROBLEM,
            value_on={"Present", "Confirmed"},
            value_off={"Off"},
        ),
        HCBinarySensorEntityDescription(
            key="binary_sensor_coffee_outlet_missing",
            entity="ConsumerProducts.CoffeeMaker.Event.CoffeeOutletMissing",
            device_class=BinarySensorDeviceClass.PROBLEM,
            value_on={"Present", "Confirmed"},
            value_off={"Off"},
        ),
        HCBinarySensorEntityDescription(
            key="binary_sensor_coffee_close_door",
            entity="ConsumerProducts.CoffeeMaker.Event.CloseDoor",
            device_class=BinarySensorDeviceClass.DOOR,
            value_on={"Present", "Confirmed"},
            value_off={"Off"},
        ),
        HCBinarySensorEntityDescription(
            key="binary_sensor_bean_container_empty",
            entity="ConsumerProducts.CoffeeMaker.Event.BeanContainerEmpty",
            device_class=BinarySensorDeviceClass.PROBLEM,
            value_on={"Present"},
            value_off={"Off", "Confirmed"},
        ),
        HCBinarySensorEntityDescription(
            key="binary_sensor_coffee_cleaning_due",
            entity="ConsumerProducts.CoffeeMaker.Event.DeviceShouldBeCleaned",
            device_class=BinarySensorDeviceClass.PROBLEM,
            value_on={"Present", "Confirmed"},
            value_off={"Off"},
        ),
        HCBinarySensorEntityDescription(
            key="binary_sensor_coffee_calc_n_clean_due",
            entity="ConsumerProducts.CoffeeMaker.Event.DeviceShouldBeCalcNCleaned",
            device_class=BinarySensorDeviceClass.PROBLEM,
            value_on={"Present", "Confirmed"},
            value_off={"Off"},
        ),
        HCBinarySensorEntityDescription(
            key="binary_sensor_coffee_clean_brewing_unit",
            entity="ConsumerProducts.CoffeeMaker.Event.CleanBrewingUnit",
            device_class=BinarySensorDeviceClass.PROBLEM,
            value_on={"Present", "Confirmed"},
            value_off={"Off"},
        ),
        HCBinarySensorEntityDescription(
            key="binary_sensor_coffee_milk_reminder",
            entity="ConsumerProducts.CoffeeMaker.Event.MilkReminder",
            device_class=BinarySensorDeviceClass.PROBLEM,
            value_on={"Present", "Confirmed"},
            value_off={"Off"},
        ),
        HCBinarySensorEntityDescription(
            key="binary_sensor_coffee_water_filter_change",
            entity="ConsumerProducts.CoffeeMaker.Event.WaterFilterShouldBeChanged",
            device_class=BinarySensorDeviceClass.PROBLEM,
            value_on={"Present", "Confirmed"},
            value_off={"Off"},
        ),
    ],
    "event_sensor": [
        HCSensorEntityDescription(
            key="sensor_water_tank",
            entities=[
                "ConsumerProducts.CoffeeMaker.Event.WaterTankEmpty",
                "ConsumerProducts.CoffeeMaker.Event.WaterTankNearlyEmpty",
                "ConsumerProducts.CoffeeMaker.Event.WaterTankNotInserted",
            ],
            device_class=SensorDeviceClass.ENUM,
            options=["empty", "nearly_empty", "not_inserted", "full"],
        ),
        HCSensorEntityDescription(
            key="sensor_drip_tray",
            entities=[
                "ConsumerProducts.CoffeeMaker.Event.DripTrayFull",
                "ConsumerProducts.CoffeeMaker.Event.DripTrayNotInserted",
            ],
            device_class=SensorDeviceClass.ENUM,
            options=["full", "not_inserted", "ok"],
        ),
        HCSensorEntityDescription(
            key="sensor_coffee_descaling",
            entities=[
                "ConsumerProducts.CoffeeMaker.Event.DeviceDescalingBlockage",
                "ConsumerProducts.CoffeeMaker.Event.DeviceDescalingOverdue",
                "ConsumerProducts.CoffeeMaker.Event.DeviceShouldBeDescaled",
            ],
            device_class=SensorDeviceClass.ENUM,
            options=["blocked", "overdue", "due", "ok"],
        ),
        HCSensorEntityDescription(
            key="sensor_coffee_care_program_step",
            entities=[
                "ConsumerProducts.CoffeeMaker.Event.EmptyDripTray",
                "ConsumerProducts.CoffeeMaker.Event.EmptyDripTrayRemoveContainer",
                "ConsumerProducts.CoffeeMaker.Event.ThrowCleaningDiscInTheDrawer",
                "ConsumerProducts.CoffeeMaker.Event.FillDescaler",
                "ConsumerProducts.CoffeeMaker.Event.EmptyMilkTank",
                "ConsumerProducts.CoffeeMaker.Event.PlaceEmptyGlassUnderOutlet",
                "ConsumerProducts.CoffeeMaker.Event.PlaceContainerUnderOutlet",
                "ConsumerProducts.CoffeeMaker.Event.CleanMilkTank",
                "ConsumerProducts.CoffeeMaker.Event.CleanFillWaterTank",
                "ConsumerProducts.CoffeeMaker.Event.RemoveContainerUnderOutlet",
                "ConsumerProducts.CoffeeMaker.Event.ServiceProgramFinished",
            ],
            device_class=SensorDeviceClass.ENUM,
            options=[
                "empty_drip_tray",
                "empty_drip_tray_remove_container",
                "insert_cleaning_tablet",
                "fill_descaler",
                "empty_milk_container",
                "place_empty_glass",
                "place_container",
                "clean_milk_container",
                "rinse_and_fill_water_tank",
                "remove_container",
                "finished",
                "none",
            ],
        ),
    ],
    "select": [
        HCSelectEntityDescription(
            key="select_coffee_temperature",
            entity="ConsumerProducts.CoffeeMaker.Option.CoffeeTemperature",
            device_class=SensorDeviceClass.ENUM,
            has_state_translation=True,
        ),
        HCSelectEntityDescription(
            key="select_bean_amount",
            entity="ConsumerProducts.CoffeeMaker.Option.BeanAmount",
            device_class=SensorDeviceClass.ENUM,
            has_state_translation=True,
        ),
        HCSelectEntityDescription(
            key="select_beverage_size",
            entity="ConsumerProducts.CoffeeMaker.Option.BeverageSize",
            device_class=SensorDeviceClass.ENUM,
            has_state_translation=True,
        ),
        HCSelectEntityDescription(
            key="select_coffee_milk_ratio",
            entity="ConsumerProducts.CoffeeMaker.Option.CoffeeMilkRatio",
            device_class=SensorDeviceClass.ENUM,
            has_state_translation=True,
        ),
        HCSelectEntityDescription(
            key="select_hot_water_temperature",
            entity="ConsumerProducts.CoffeeMaker.Option.HotWaterTemperature",
            device_class=SensorDeviceClass.ENUM,
            has_state_translation=True,
        ),
        HCSelectEntityDescription(
            key="select_flow_rate",
            entity="ConsumerProducts.CoffeeMaker.Option.FlowRate",
            device_class=SensorDeviceClass.ENUM,
            has_state_translation=True,
        ),
        HCSelectEntityDescription(
            key="select_coarsness",
            entity="ConsumerProducts.CoffeeMaker.Option.Coarsness",
            device_class=SensorDeviceClass.ENUM,
            has_state_translation=True,
        ),
        HCSelectEntityDescription(
            key="select_coffee_strength",
            entity="ConsumerProducts.CoffeeMaker.Option.CoffeeStrength",
            device_class=SensorDeviceClass.ENUM,
            has_state_translation=True,
        ),
        HCSelectEntityDescription(
            key="select_aroma_select",
            entity="ConsumerProducts.CoffeeMaker.Option.AromaSelect",
            device_class=SensorDeviceClass.ENUM,
            has_state_translation=True,
        ),
        HCSelectEntityDescription(
            key="select_bean_container",
            entity="ConsumerProducts.CoffeeMaker.Option.BeanContainerSelection",
            device_class=SensorDeviceClass.ENUM,
            has_state_translation=True,
        ),
        HCSelectEntityDescription(
            key="select_shot_count",
            entity="ConsumerProducts.CoffeeMaker.Option.Shot.Count",
            device_class=SensorDeviceClass.ENUM,
            has_state_translation=True,
        ),
        HCSelectEntityDescription(
            key="select_cups",
            entity="ConsumerProducts.CoffeeMaker.Option.Cups",
            device_class=SensorDeviceClass.ENUM,
            has_state_translation=True,
        ),
        HCSelectEntityDescription(
            key="select_coffee_switch_off_after",
            entity="ConsumerProducts.CoffeeMaker.Setting.SwitchOffAfter",
            entity_category=EntityCategory.CONFIG,
            has_state_translation=True,
        ),
        HCSelectEntityDescription(
            key="select_coffee_water_hardness",
            entity="ConsumerProducts.CoffeeMaker.Setting.WaterHardness",
            entity_category=EntityCategory.CONFIG,
            has_state_translation=True,
        ),
        HCSelectEntityDescription(
            key="select_coffee_user_mode",
            entity="ConsumerProducts.CoffeeMaker.Setting.UserMode",
            entity_category=EntityCategory.CONFIG,
            has_state_translation=True,
        ),
        HCSelectEntityDescription(
            key="select_coffee_milk_order",
            entity="ConsumerProducts.CoffeeMaker.Setting.CoffeeMilkOrder",
            entity_category=EntityCategory.CONFIG,
            entity_registry_enabled_default=False,
            has_state_translation=True,
        ),
        HCSelectEntityDescription(
            key="select_coffee_macchiato_pause",
            entity="ConsumerProducts.CoffeeMaker.Setting.MacchiatoPause",
            entity_category=EntityCategory.CONFIG,
            entity_registry_enabled_default=False,
            has_state_translation=True,
        ),
        HCSelectEntityDescription(
            key="select_coffee_milk_reminder",
            entity="ConsumerProducts.CoffeeMaker.Setting.RemindForMilkAfter",
            entity_category=EntityCategory.CONFIG,
            entity_registry_enabled_default=False,
            has_state_translation=True,
        ),
        HCSelectEntityDescription(
            key="select_coffee_default_bean_container",
            entity="ConsumerProducts.CoffeeMaker.Setting.DefaultBeanContainerSelection",
            entity_category=EntityCategory.CONFIG,
            entity_registry_enabled_default=False,
            has_state_translation=True,
        ),
    ],
    "switch": [
        HCSwitchEntityDescription(
            key="switch_multiple_beverages",
            entity="ConsumerProducts.CoffeeMaker.Option.MultipleBeverages",
            device_class=SwitchDeviceClass.SWITCH,
        ),
        HCSwitchEntityDescription(
            key="switch_cup_warmer",
            entity="ConsumerProducts.CoffeeMaker.Setting.CupWarmer",
            device_class=SwitchDeviceClass.SWITCH,
        ),
        HCSwitchEntityDescription(
            key="switch_coffee_leave_profiles_automatically",
            entity="ConsumerProducts.CoffeeMaker.Setting.LeaveProfilesAutomatically",
            device_class=SwitchDeviceClass.SWITCH,
            entity_category=EntityCategory.CONFIG,
            entity_registry_enabled_default=False,
        ),
    ],
    "number": [
        HCNumberEntityDescription(
            key="number_fill_quantity",
            entity="ConsumerProducts.CoffeeMaker.Option.FillQuantity",
            device_class=NumberDeviceClass.VOLUME,
            native_unit_of_measurement=UnitOfVolume.MILLILITERS,
            mode=NumberMode.BOX,
        ),
        HCNumberEntityDescription(
            key="number_coffee_display_brightness",
            entity="ConsumerProducts.CoffeeMaker.Setting.BrightnessDisplay",
            entity_category=EntityCategory.CONFIG,
            entity_registry_enabled_default=False,
            mode=NumberMode.AUTO,
        ),
    ],
    "sensor": [
        HCSensorEntityDescription(
            key="sensor_countdown_calc_n_clean",
            entity="ConsumerProducts.CoffeeMaker.Status.BeverageCountdownCalcNClean",
            entity_registry_enabled_default=False,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        HCSensorEntityDescription(
            key="sensor_countdown_cleaning",
            entity="ConsumerProducts.CoffeeMaker.Status.BeverageCountdownCleaning",
            entity_registry_enabled_default=False,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        HCSensorEntityDescription(
            key="sensor_countdown_descaling",
            entity="ConsumerProducts.CoffeeMaker.Status.BeverageCountdownDescaling",
            entity_registry_enabled_default=False,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        HCSensorEntityDescription(
            key="sensor_countdown_water_filter",
            entity="ConsumerProducts.CoffeeMaker.Status.BeverageCountdownWaterfilter",
            entity_registry_enabled_default=False,
            state_class=SensorStateClass.MEASUREMENT,
        ),
        HCSensorEntityDescription(
            key="sensor_count_ristretto_espresso",
            entity="ConsumerProducts.CoffeeMaker.Status.BeverageCounterRistrettoEspresso",
            entity_registry_enabled_default=False,
            state_class=SensorStateClass.TOTAL_INCREASING,
        ),
        HCSensorEntityDescription(
            key="sensor_count_coffee",
            entity="ConsumerProducts.CoffeeMaker.Status.BeverageCounterCoffee",
            entity_registry_enabled_default=False,
            state_class=SensorStateClass.TOTAL_INCREASING,
        ),
        HCSensorEntityDescription(
            key="sensor_count_coffee_milk",
            entity="ConsumerProducts.CoffeeMaker.Status.BeverageCounterCoffeeAndMilk",
            entity_registry_enabled_default=False,
            state_class=SensorStateClass.TOTAL_INCREASING,
        ),
        HCSensorEntityDescription(
            key="sensor_count_frothy_milk",
            entity="ConsumerProducts.CoffeeMaker.Status.BeverageCounterFrothyMilk",
            entity_registry_enabled_default=False,
            state_class=SensorStateClass.TOTAL_INCREASING,
        ),
        HCSensorEntityDescription(
            key="sensor_count_hot_milk",
            entity="ConsumerProducts.CoffeeMaker.Status.BeverageCounterHotMilk",
            entity_registry_enabled_default=False,
            state_class=SensorStateClass.TOTAL_INCREASING,
        ),
        HCSensorEntityDescription(
            key="sensor_count_hot_water",
            entity="ConsumerProducts.CoffeeMaker.Status.BeverageCounterHotWater",
            entity_registry_enabled_default=False,
            state_class=SensorStateClass.TOTAL_INCREASING,
        ),
        HCSensorEntityDescription(
            key="sensor_count_hot_water_cups",
            entity="ConsumerProducts.CoffeeMaker.Status.BeverageCounterHotWaterCups",
            entity_registry_enabled_default=False,
            state_class=SensorStateClass.TOTAL_INCREASING,
        ),
        HCSensorEntityDescription(
            key="sensor_count_powder_coffee",
            entity="ConsumerProducts.CoffeeMaker.Status.BeverageCounterPowderCoffee",
            entity_registry_enabled_default=False,
            state_class=SensorStateClass.TOTAL_INCREASING,
        ),
        HCSensorEntityDescription(
            key="sensor_coffeemaker_process_phase",
            entity="ConsumerProducts.CoffeeMaker.Status.ProcessPhase",
            entity_registry_enabled_default=False,
            device_class=SensorDeviceClass.ENUM,
            has_state_translation=True,
        ),
    ],
}
