name: Lint

on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: "3.14"
      - run: |
          pip install uv
          uv sync --no-install-project --prerelease=allow
      - run: |
          uv run ruff format --diff custom_components/
          uv run ruff format --diff tests/
      - run: |
          uv run ruff check custom_components/
          uv run ruff check tests/
      - run: |
          uv run mypy custom_components/homeconnect_ws
