name: Release
on:
  release:
    types: [published]
jobs:
  release_zip_file:
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - shell: bash
        run: |
          version="${{ github.event.release.tag_name }}"
          version="${version,,}"
          yq e -P -o=json \
            -i ".version = \"${version}\"" \
            "${{ github.workspace }}/custom_components/homeconnect_ws/manifest.json"
      - run: |
          cd ${{ github.workspace }}/custom_components/homeconnect_ws
          zip homeconnect_ws.zip -r ./
      - name: Upload release asset
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "$RELEASE_TAG" "${{ github.workspace }}/custom_components/homeconnect_ws/homeconnect_ws.zip"
